# https://github.com/elastic/dockerfiles/blob/794a8cd3e34dd08e354838195e1c90d22d08467d/elasticsearch/Dockerfile
FROM docker.elastic.co/elasticsearch/elasticsearch:7.4.2

COPY --chown=elasticsearch:elasticsearch ./elasticsearch-data.yml /usr/share/elasticsearch/config/elasticsearch.yml

RUN bin/elasticsearch-plugin install --batch [repository-gcs,discovery-gce] --silent \
  && bin/elasticsearch-plugin install https://github.com/medcl/elasticsearch-analysis-ik/releases/download/v7.4.2/elasticsearch-analysis-ik-7.4.2.zip --silent

EXPOSE 9200 9300

ENTRYPOINT ["/usr/local/bin/docker-entrypoint.sh"]
CMD ["eswrapper"]